### PR TITLE
Adds database parameter

### LINKED ISSUE #157: get_tables_by_prefix_sql does not pass on database parameter
Looks like the `database` parameter does not get passed on to the adapter macro here

```
{% macro get_tables_by_prefix_sql(schema, prefix, exclude='', database=target.database) %}
    {{ adapter_macro('dbt_utils.get_tables_by_prefix_sql', schema, prefix, exclude) }}
{% endmacro %}
```
Should be: 
```
{% macro get_tables_by_prefix_sql(schema, prefix, exclude='', database=target.database) %}
    {{ adapter_macro('dbt_utils.get_tables_by_prefix_sql', schema, prefix, exclude, database) }}
{% endmacro %}
```
No?

### PR DESCRIPTION
**Pull request by clausherther**
Fixes #157

### CODE REVIEW

**Comment by drewbanin** [comment]
Thanks @clausherther - this looks great :) 

Just kicked off the tests here

**Comment by clausherther** [comment]
Thanks! Are you planning a release any time soon, or should I plan on using master maybe? Or run a local version instead for now?

**Comment by drewbanin** [comment]
@clausherther we can cut a new release (0.2.2) with this change once this PR is merged

**Comment by clausherther** [comment]
Awesome, thx!

**Comment by drewbanin** [comment]
@clausherther alright! This LGTM. I'm going to merge this now, but wait until Monday to cut a new release. I think the last time I did a `dbt-utils` release on a Friday night, there were a couple of angry analysts out there on Saturday morning :)

**Comment by drewbanin** [comment]
Released here: https://github.com/fishtown-analytics/dbt-utils/releases/tag/0.2.2

Will be up on hub.getdbt.com within the next hour :)

Thanks again!

**Comment by clausherther** [comment]
Awesome, thx!!

**Pull request merged**
