### PR TITLE
Change some docs urls on README.md

### PR DESCRIPTION
**Pull request by captainEli**
I noticed a url wasn't working on the dbt_utils README today. I made a quick PR to fix that. Let me know if I need to change anything!

### CODE REVIEW

**Comment by clrcrl** [comment]
Thanks for this @captainEli!

@drewbanin -- I thought our CI would pick these up?

**Comment by drewbanin** [comment]
@clrcrl this is in dbt-utils!! We don't have link checking turned on for docs.getdbt.com here :)

**Comment by clrcrl** [comment]
Oh lol, sorry I did what you did yesterday, and assumed this was in `docs.getdbt.com` :)

**Comment by drewbanin** [comment]
2 many repos!

**Pull request merged**
