### PR TITLE
Add sql_delimited_list macro

### PR DESCRIPTION
**Pull request by clrcrl**
Wrote this macro for a query I was writing. Thought it might be useful to share. Feedback welcome 😄

### CODE REVIEW

**Comment by clrcrl** [comment]
@drewbanin – those integration tests all failed locally, but I haven't touched them. Any ideas?

**Comment by jthandy** [comment]
Sometimes it's useful to use other delimeters -- for example, `|` in redshift to coalesce things! i'd recommend adding a `delimeter` argument.

**Comment by clrcrl** [comment]
@jthandy  –  I did consider that as well!
In that case, would you remove the `(` and `)` from the macro? I wrote it assuming it would be used for `in` statements, so put the brackets in there, but they won't be useful for coalescing.

**Comment by clrcrl** [comment]
Wait a second, just realised I can pretty easily accomplish this with:
`{{ listx|join(', ') }}`
In which case I probably don't need to write a macro for it... 😅

**Comment by jthandy** [comment]
Yeah I was going to mention that also but glad to see you got there on your own :D Always happy to bounce ideas around before you put together a full PR including documentation and unit tests just to make sure that we're all on the same page about how to accomplish something!

**Pull request closed without merging**
