### PR TITLE
get_tables_by_prefix, ideal for union_tables jobs

### PR DESCRIPTION
**Pull request by jdub**
Solution suggested by @drewbanin, enhanced with "exclude" parameter.

### CODE REVIEW

**Comment by jdub** [comment]
This works _great_ without the `adapter_macro` wrapper, but when I add it, I get this error:
```
Encountered an error:
not enough values to unpack (expected 2, got 1)
```

**Comment by drewbanin** [comment]
@jdub this is great! I believe the `not enough values to unpack (expected 2, got 1)` error you're seeing was fixed in `0.9.1` (released 1/5). You could try upgrading to see if that fixes this.

Separately, I noticed a [bug](https://github.com/fishtown-analytics/dbt/issues/635) in how dbt implements `adapter_macro` which I think will prevent this particular macro from working correctly (for now).

I think the best solution in the short term would be to nix the `adapter_macro` approach, and instead just place the `get_tables_by_prefix` macro somewhere like `macros/sql/get_tables_by_prefix.sql`.

If it makes sense to extend this macro to other adapters in the future, we can definitely do that without breaking backwards compatibility.

**Comment by jdub** [comment]
Not fixed in 0.9.1 sadly:

```
$ dbt --version
installed version: 0.9.1
   latest version: 0.9.1
Up to date!
$ dbt run --models awsbilling








  []

Encountered an error:
not enough values to unpack (expected 2, got 1)
```

Thanks -- I'll update with your suggested change.

**Comment by drewbanin** [comment]
@jdub let me know when this is ready for another look. Can you also add documentation to the `README.md` file?

**Comment by jdub** [comment]
@drewbanin README updated, with a bit of alphabetical re-ordering for good measure. This is good to go.

**Comment by drewbanin** [comment]
@jdub groovy - this LGTM! Merging

**Pull request merged**
