### PR TITLE
Make star macro case insensitive

### PR DESCRIPTION
**Pull request by mdimercurio**
This is a:
- [ ] bug fix PR with no breaking changes (please change the base branch to `main`)
- [ ] new functionality
- [x] a breaking change

## Description & motivation

This change makes the `except` parameter of the `star` macro case insensitive.

We encountered this issue as we are migrating from Postgres to Snowflake and we lowercase all of our column names in the `except` argument.

This could be a breaking change if you have different columns with different casing but this seems like a very bad practice, for example `timestamp` and `Timestamp` in the same table. I haven't included an entry in the changelog yet because I am not sure if this is considered a fix/feature/breaking change.

See discussion here: https://github.com/fishtown-analytics/dbt-utils/issues/115

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to the changelog

### CODE REVIEW

**Comment by clrcrl** [comment]
@drewbanin — you left the original comment about making the `except` parameter case-insensitive. I know it has probably been a while since you thought about it, but do you have any thoughts here?

**Comment by drewbanin** [comment]
hey @mdimercurio - thanks for opening this PR!

Gosh... it has been a while. My sense is still that it would be more convenient to make the `except` argument case-insensitive, although it definitely is "messy" to create subtleties like these ad-hoc across the different macros in dbt-utils.

@clrcrl what do you reckon?

**Comment by mdimercurio** [comment]
@drewbanin do you see other macros that could use this logic?
We could add an argument to enable it to make it more clear to users

**Comment by clrcrl** [comment]
Closing in favor of #348

**Pull request closed without merging**
